language: ruby
rvm:
  - 2.2.3
env:
  - DB=sqlite
before_script:
  - export DISPLAY=:0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 
  - sleep 3
cache: bundler

before_install: 
  - gem update --system
  - bundle install
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake
bundler_args: --binstubs=./bundler_stubs

after_success:
  - coveralls