# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b7720bf956605937b36a536a6ec97ee12bf71182391578976f52ec3ee3ee50fecb5431e6a0e3eb944146cd38515dbf6835cf4ee206d653333ee322dfcf8dec6

test:
  secret_key_base: 0673007718430e4010472810f0f88196d9ad035307e691008eef9993e29e69bcc2cff9222d2e408380207b182294eabf915987c14df598e4c27c9b7e14347a73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
